# Generated by Django 4.1.6 on 2023-03-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commnent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnent',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='psot',
            new_name='post',
        ),
    ]
